// V3G: the V3T kernel of tr_ring.cu (stages 2 -> 3 chained in registers on PTX mma.sync, tokens
// stacked into the mma M dimension) with the modes as template parameters and FP16 or BF16
// elements, so that any shape can get a fixed-size variant. The algorithm, the shared-memory map
// and the design-B finish are those of tr_ring_fused_v3t_kernel; only these changed:
//   - ni, nj, nk, P, Q, Rr come from Modes<...> instead of namespace constants
//   - the element type E (FP16 / BF16): mma.sync .f16 or .bf16, conversions through Ops<E>
//   - design B only (the submission default); T = 1 is V3T with TT = 16 / P token rows
//   - NT threads per block (256 or 512) and KS: each warp item (q, m tiles) is cut into KS
//     independent pieces over the block's k values (kk = ks, ks + KS, ...), each adding its
//     partial Y into the FP32 workspace. More, shorter items for the warps: Nsight Compute showed
//     the block waiting on the longest warp (9 items on 8 warps at QC = 9)
//   - CL: a thread-block cluster of CL blocks = CL ring links a of one (k chunk, q chunk, token
//     tile). CL > 1: the partial Y goes to shared memory (sY), the cluster sums the CL links
//     through distributed shared memory (Hopper), then ONE red.add per output per cluster
//     instead of CL. tools/v3g_ablate.py: the red.adds were 35-40% of an R = 8 call
// Compiled tilings: tilings.h (generated by tools/gen_v3g_tilings.py), one .cu file per shape.
#pragma once
#include <torch/extension.h>
#include <ATen/cuda/CUDAContext.h>
#include <c10/cuda/CUDAGuard.h>
#include <cuda_bf16.h>
#include <cuda_fp16.h>
#include <cooperative_groups.h>

namespace v3g {

constexpr int kThreads = 256, kWarps = kThreads / 32;
__host__ __device__ constexpr int round16(int v) { return (v + 15) / 16 * 16; }
__host__ __device__ constexpr size_t a128(size_t v) { return (v + 127) & ~size_t(127); }

template <int NI, int NJ, int NK, int P_, int Q_, int RR>
struct Modes {
  static constexpr int ni = NI, nj = NJ, nk = NK, P = P_, Q = Q_, Rr = RR;
};

template <class E> struct Ops;
template <> struct Ops<__half> {
  __device__ static void mma16816(float (&d)[4], unsigned a0, unsigned a1, unsigned a2,
                                  unsigned a3, unsigned b0, unsigned b1) {
    asm volatile(
        "mma.sync.aligned.m16n8k16.row.col.f32.f16.f16.f32 {%0,%1,%2,%3}, {%4,%5,%6,%7}, "
        "{%8,%9}, {%0,%1,%2,%3};"
        : "+f"(d[0]), "+f"(d[1]), "+f"(d[2]), "+f"(d[3])
        : "r"(a0), "r"(a1), "r"(a2), "r"(a3), "r"(b0), "r"(b1));
  }
  __device__ static void mma1688(float (&d)[4], unsigned a0, unsigned a1, unsigned b0) {
    asm volatile(
        "mma.sync.aligned.m16n8k8.row.col.f32.f16.f16.f32 {%0,%1,%2,%3}, {%4,%5}, {%6}, "
        "{%0,%1,%2,%3};"
        : "+f"(d[0]), "+f"(d[1]), "+f"(d[2]), "+f"(d[3])
        : "r"(a0), "r"(a1), "r"(b0));
  }
  __device__ static unsigned pack_f2(float lo, float hi) {
    __half2 h = __floats2half2_rn(lo, hi);
    return *reinterpret_cast<unsigned*>(&h);
  }
  __device__ static unsigned pack_e2(__half lo, __half hi) {
    __half2 h = __halves2half2(lo, hi);
    return *reinterpret_cast<unsigned*>(&h);
  }
  __device__ static float2 to_f2(unsigned u) {
    return __half22float2(*reinterpret_cast<const __half2*>(&u));
  }
  __device__ static float to_f(__half v) { return __half2float(v); }
};
template <> struct Ops<__nv_bfloat16> {
  __device__ static void mma16816(float (&d)[4], unsigned a0, unsigned a1, unsigned a2,
                                  unsigned a3, unsigned b0, unsigned b1) {
    asm volatile(
        "mma.sync.aligned.m16n8k16.row.col.f32.bf16.bf16.f32 {%0,%1,%2,%3}, {%4,%5,%6,%7}, "
        "{%8,%9}, {%0,%1,%2,%3};"
        : "+f"(d[0]), "+f"(d[1]), "+f"(d[2]), "+f"(d[3])
        : "r"(a0), "r"(a1), "r"(a2), "r"(a3), "r"(b0), "r"(b1));
  }
  __device__ static void mma1688(float (&d)[4], unsigned a0, unsigned a1, unsigned b0) {
    asm volatile(
        "mma.sync.aligned.m16n8k8.row.col.f32.bf16.bf16.f32 {%0,%1,%2,%3}, {%4,%5}, {%6}, "
        "{%0,%1,%2,%3};"
        : "+f"(d[0]), "+f"(d[1]), "+f"(d[2]), "+f"(d[3])
        : "r"(a0), "r"(a1), "r"(b0));
  }
  __device__ static unsigned pack_f2(float lo, float hi) {
    __nv_bfloat162 h = __floats2bfloat162_rn(lo, hi);
    return *reinterpret_cast<unsigned*>(&h);
  }
  __device__ static unsigned pack_e2(__nv_bfloat16 lo, __nv_bfloat16 hi) {
    __nv_bfloat162 h = __halves2bfloat162(lo, hi);
    return *reinterpret_cast<unsigned*>(&h);
  }
  __device__ static float2 to_f2(unsigned u) {
    return __bfloat1622float2(*reinterpret_cast<const __nv_bfloat162*>(&u));
  }
  __device__ static float to_f(__nv_bfloat16 v) { return __bfloat162float(v); }
};

template <class E>
__device__ __forceinline__ unsigned lds_u32(const E* p) {
  return *reinterpret_cast<const unsigned*>(p);
}
__device__ __forceinline__ void cp_async16(void* dst, const void* src, int src_bytes) {
  asm volatile("cp.async.cg.shared.global [%0], [%1], 16, %2;" ::"r"(
                   (unsigned)__cvta_generic_to_shared(dst)),
               "l"(src), "r"(src_bytes)
               : "memory");
}
__device__ __forceinline__ void red_add_v2(float* p, float a, float b) {
#if __CUDA_ARCH__ >= 900
  asm volatile("red.global.add.v2.f32 [%0], {%1, %2};" ::"l"(p), "f"(a), "f"(b) : "memory");
#else
  atomicAdd(p, a);
  atomicAdd(p + 1, b);
#endif
}

// Same shared-memory map as CfgT in tr_ring.cu (E is 2 bytes either way)
template <class M, int R, int KC, int QC, int TT, int MG, int CL = 1>
struct Cfg {
  static constexpr int ni = M::ni, nj = M::nj, nk = M::nk, P = M::P, Q = M::Q, Rr = M::Rr;
  static constexpr int Rc = round16(R), Rrp = round16(Rr), Rrs = Rrp + 8;
  static constexpr int K2p = round16(nj * R), K2s = K2p + 8, N2c = Q * Rc;
  static constexpr int Nb = QC * Rc, N2s = Nb + 8, PR = P * R;
  static constexpr int Mr = round16(TT * P), MT = Mr / 16;
  static constexpr int nkc = (nk + KC - 1) / KC, nqc = (Q + QC - 1) / QC;
  static constexpr int kt_n = K2p / 16, NC8 = R / 8, RT = (Rr + 7) / 8;
  static constexpr size_t b_off = 0;
  static constexpr size_t a_off = a128(b_off + 2 * K2p * N2s);
  static constexpr size_t c_off = a128(a_off + 2 * ni * PR);
  static constexpr size_t x_off = a128(c_off + 2 * KC * Rc * Rrs);
  static constexpr size_t s1_off = a128(x_off + sizeof(float) * KC * TT * ni * nj);
  static constexpr size_t y_off = a128(s1_off + 2 * KC * Mr * K2s);   // sY (CL > 1 only)
  static constexpr size_t smem = CL > 1 ? a128(y_off + sizeof(float) * QC * Mr * Rrp) : y_off;
  static_assert(CL >= 1 && CL <= 8 && R % CL == 0, "V3G: CL in 1..8 dividing R");
  static_assert(R == 8 || R == 16, "V3G: R = 8 or 16");
  static_assert((TT * P) % 16 == 0, "V3G: TT * P must fill whole m16 tiles");
  static_assert(MT % MG == 0, "V3G: MG must divide the m tiles");
  static_assert(nj % 4 == 0, "V3G: stage 1 reads x in float4 along j");
  static_assert(Rr % 4 == 0, "V3G: the design-B finish converts float4 along r");
  static_assert((ni * PR) % 8 == 0, "V3G: A slice copied in 16-byte pieces");
  static constexpr int NG = MT / MG;  // m-tile groups per q
};

template <class M, class E, int R, int KC, int QC, int TT, int MG, int NT, int KS, int CL>
__global__ void __launch_bounds__(NT)
v3g_kernel(const E* __restrict__ x,    // [T, ni*nj*nk]
           const E* __restrict__ A1,   // [R(a)][ni][P*R (p,b)]
           const E* __restrict__ B2,   // [K2p (j,b)][N2c (q,c)]
           const E* __restrict__ C3,   // [nk][R(a)][Rc (c)][Rrp (r)]
           float* __restrict__ ws,     // [T, P*Q*Rr] FP32 accumulator, zero between calls
           E* __restrict__ y,          // [T, P*Q*Rr]
           unsigned int* __restrict__ tile_done,  // [ntt * nqc], zero between calls
           int T, int ablate) {  // ablate: measurement only, 0 in use
  using C = Cfg<M, R, KC, QC, TT, MG, CL>;
  using O = Ops<E>;
  static_assert(KS >= 1 && KS <= KC, "V3G: 1 <= KS <= KC");
  static_assert(CL == 1 || KS == 1, "V3G: the cluster sum needs one writer per sY value");
  constexpr int ni = C::ni, nj = C::nj, nk = C::nk, P = C::P, Q = C::Q, Rr = C::Rr;
  constexpr int Rc = C::Rc, Rrs = C::Rrs, K2s = C::K2s, N2s = C::N2s, PR = C::PR;
  constexpr int kt_n = C::kt_n, RT = C::RT, out_f = P * Q * Rr, in_f = ni * nj * nk;
  extern __shared__ __align__(128) unsigned char smem[];
  E* sB = reinterpret_cast<E*>(smem + C::b_off);
  E* sA = reinterpret_cast<E*>(smem + C::a_off);
  E* sC = reinterpret_cast<E*>(smem + C::c_off);
  float* sX = reinterpret_cast<float*>(smem + C::x_off);
  E* sS1 = reinterpret_cast<E*>(smem + C::s1_off);
  const int tid = threadIdx.x, warp = tid / 32, lane = tid % 32, g = lane >> 2, t4 = lane & 3;
  // CL > 1: the link a runs fastest, so CL consecutive blocks (one cluster) are CL links of
  // the same (k chunk, q chunk, token tile)
  int u = blockIdx.x, a, kci, qci, tti;
  if constexpr (CL > 1) {
    a = u % R;
    u /= R;
    kci = u % C::nkc;
    u /= C::nkc;
    qci = u % C::nqc;
    tti = u / C::nqc;
  } else {
    kci = u % C::nkc;
    u /= C::nkc;
    qci = u % C::nqc;
    u /= C::nqc;
    a = u % R;
    tti = u / R;
  }
  const int k0 = kci * KC, q0 = qci * QC, t0 = tti * TT;
  const int qc_valid = min(QC, Q - q0), kc_valid = min(KC, nk - k0), tt_valid = min(TT, T - t0);

  {  // ---- cores slice: cp.async into shared memory, zero-fill for padding
    constexpr int brow = C::Nb / 8, bstride = N2s / 8, grow = C::N2c / 8;
    const int valid8 = qc_valid * Rc / 8, col0 = q0 * Rc / 8;
    const int4* gB = reinterpret_cast<const int4*>(B2);
    for (int e = tid; e < C::K2p * brow; e += NT) {
      const int row = e / brow, col = e % brow;
      const bool ok = col < valid8;
      cp_async16(reinterpret_cast<int4*>(sB) + row * bstride + col,
                 gB + row * grow + col0 + (ok ? col : 0), ok ? 16 : 0);
    }
    constexpr int crow = C::Rrp / 8, cstride = Rrs / 8, cvec = Rc * crow;
    const int4* gC = reinterpret_cast<const int4*>(C3);
    for (int e = tid; e < KC * cvec; e += NT) {
      const int kk = e / cvec, c = (e % cvec) / crow, col = e % crow;
      const bool ok = kk < kc_valid;
      cp_async16(reinterpret_cast<int4*>(sC) + (kk * Rc + c) * cstride + col,
                 gC + ((size_t)(k0 + (ok ? kk : 0)) * R + a) * cvec + e % cvec, ok ? 16 : 0);
    }
    const int4* gA = reinterpret_cast<const int4*>(A1 + (size_t)a * ni * PR);
    for (int e = tid; e < ni * PR / 8; e += NT)
      cp_async16(reinterpret_cast<int4*>(sA) + e, gA + e, 16);
    asm volatile("cp.async.commit_group;" ::: "memory");
  }
  // ---- x slice: sX[kk][t][i][j] = x[t0 + t, i, j, k0 + kk] (FP32), zero for missing k / t
  for (int e = tid; e < KC * TT * ni * nj; e += NT) {
    const int kk = e % KC, ij = (e / KC) % (ni * nj), tl = e / (KC * ni * nj);
    sX[(kk * TT + tl) * ni * nj + ij] =
        kk < kc_valid && tl < tt_valid
            ? O::to_f(x[(size_t)(t0 + tl) * in_f + ij * nk + k0 + kk]) : 0.f;
  }
  asm volatile("cp.async.wait_all;" ::: "memory");
  __syncthreads();

  // ---- stage 1, every k and token at once: S1[kk][t*P + p][j*R + b] = sum_i x * A
  {
    constexpr int J4 = nj / 4, B4 = R / 4, tasks = TT * P * J4 * B4;
    for (int e = tid; e < kc_valid * tasks; e += NT) {
      const int kk = e / tasks, f = e % tasks;
      const int b4 = f % B4, j4 = (f / B4) % J4, p = (f / (B4 * J4)) % P, tl = f / (B4 * J4 * P);
      const float* xk = sX + (kk * TT + tl) * ni * nj;
      float acc[4][4] = {};
#pragma unroll 4
      for (int i = 0; i < ni; ++i) {
        const float4 xv = *reinterpret_cast<const float4*>(xk + i * nj + j4 * 4);
        const uint2 au = *reinterpret_cast<const uint2*>(sA + i * PR + p * R + b4 * 4);
        const float2 lo = O::to_f2(au.x), hi = O::to_f2(au.y);
        const float xs[4] = {xv.x, xv.y, xv.z, xv.w}, as[4] = {lo.x, lo.y, hi.x, hi.y};
#pragma unroll
        for (int uu = 0; uu < 4; ++uu)
#pragma unroll
          for (int v = 0; v < 4; ++v) acc[uu][v] += xs[uu] * as[v];
      }
      E* s1 = sS1 + (size_t)kk * C::Mr * K2s + (tl * P + p) * K2s;
#pragma unroll
      for (int uu = 0; uu < 4; ++uu) {
        unsigned* dst = reinterpret_cast<unsigned*>(s1 + (j4 * 4 + uu) * R + b4 * 4);
        dst[0] = O::pack_f2(acc[uu][0], acc[uu][1]);
        dst[1] = O::pack_f2(acc[uu][2], acc[uu][3]);
      }
    }
  }
  __syncthreads();

  // ---- stages 2 -> 3 in registers, one item (q, MG m tiles) at a time per warp
  for (int it = warp; it < qc_valid * C::NG * KS; it += (NT / 32)) {
    const int ql = it / (C::NG * KS), mt0 = ((it / KS) % C::NG) * MG, ks = it % KS;
    float yv[MG][RT][4];
#pragma unroll
    for (int mg = 0; mg < MG; ++mg)
#pragma unroll
      for (int rt = 0; rt < RT; ++rt)
        yv[mg][rt][0] = yv[mg][rt][1] = yv[mg][rt][2] = yv[mg][rt][3] = 0.f;
    const int colq = ql * Rc;
    constexpr bool kHoistB = (R == 8 && kt_n <= 16);  // the item's B fragments in registers
    unsigned bh[kHoistB ? kt_n : 1][2];
    if constexpr (kHoistB) {
#pragma unroll
      for (int kt = 0; kt < kt_n; ++kt) {
        const int kb = kt * 16 + 2 * t4, n = colq + g;
        bh[kt][0] = O::pack_e2(sB[kb * N2s + n], sB[(kb + 1) * N2s + n]);
        bh[kt][1] = O::pack_e2(sB[(kb + 8) * N2s + n], sB[(kb + 9) * N2s + n]);
      }
    }
    for (int kk = ks; kk < kc_valid; kk += KS) {
      const E* s1 = sS1 + (size_t)kk * C::Mr * K2s + mt0 * 16 * K2s;
      float acc[MG][C::NC8][4];
#pragma unroll
      for (int mg = 0; mg < MG; ++mg)
#pragma unroll
        for (int nc = 0; nc < C::NC8; ++nc)
          acc[mg][nc][0] = acc[mg][nc][1] = acc[mg][nc][2] = acc[mg][nc][3] = 0.f;
#pragma unroll
      for (int kt = 0; kt < kt_n; ++kt) {  // stage 2: MG independent chains over K = (j,b)
        const int kb = kt * 16 + 2 * t4;
        unsigned b0[C::NC8], b1[C::NC8];
#pragma unroll
        for (int nc = 0; nc < C::NC8; ++nc) {
          if constexpr (kHoistB) {
            b0[nc] = bh[kt][0];
            b1[nc] = bh[kt][1];
          } else {
            const int n = colq + nc * 8 + g;
            b0[nc] = O::pack_e2(sB[kb * N2s + n], sB[(kb + 1) * N2s + n]);
            b1[nc] = O::pack_e2(sB[(kb + 8) * N2s + n], sB[(kb + 9) * N2s + n]);
          }
        }
#pragma unroll
        for (int mg = 0; mg < MG; ++mg) {
          const E* s1m = s1 + mg * 16 * K2s;
          const unsigned a0 = lds_u32(s1m + g * K2s + kb), a1 = lds_u32(s1m + (g + 8) * K2s + kb);
          const unsigned a2 = lds_u32(s1m + g * K2s + kb + 8);
          const unsigned a3 = lds_u32(s1m + (g + 8) * K2s + kb + 8);
#pragma unroll
          for (int nc = 0; nc < C::NC8; ++nc)
            O::mma16816(acc[mg][nc], a0, a1, a2, a3, b0[nc], b1[nc]);
        }
      }
      const E* ck = sC + kk * Rc * Rrs;  // stage 3: Y += acc (as E, the A operand) @ C[c, r]
      unsigned sa[MG][4];
#pragma unroll
      for (int mg = 0; mg < MG; ++mg) {
        sa[mg][0] = O::pack_f2(acc[mg][0][0], acc[mg][0][1]);
        sa[mg][1] = O::pack_f2(acc[mg][0][2], acc[mg][0][3]);
        if constexpr (R == 16) {
          sa[mg][2] = O::pack_f2(acc[mg][1][0], acc[mg][1][1]);
          sa[mg][3] = O::pack_f2(acc[mg][1][2], acc[mg][1][3]);
        }
      }
#pragma unroll
      for (int rt = 0; rt < RT; ++rt) {  // one C fragment per rt, shared by the MG tiles
        const int r = rt * 8 + g;
        const unsigned c0 = O::pack_e2(ck[(2 * t4) * Rrs + r], ck[(2 * t4 + 1) * Rrs + r]);
        if constexpr (R == 8) {
#pragma unroll
          for (int mg = 0; mg < MG; ++mg) O::mma1688(yv[mg][rt], sa[mg][0], sa[mg][1], c0);
        } else {
          const unsigned c1 =
              O::pack_e2(ck[(2 * t4 + 8) * Rrs + r], ck[(2 * t4 + 9) * Rrs + r]);
#pragma unroll
          for (int mg = 0; mg < MG; ++mg)
            O::mma16816(yv[mg][rt], sa[mg][0], sa[mg][1], sa[mg][2], sa[mg][3], c0, c1);
        }
      }
    }
    // Y rows g, g+8 of each m tile = rows m = t*P + p; columns r = 8 rt + 2 t4, +1
    const int q = q0 + ql;
#pragma unroll
    for (int mg = 0; mg < MG; ++mg) {
      const int m0 = (mt0 + mg) * 16 + g, m1 = m0 + 8;
      const int tl0 = m0 / P, p0 = m0 % P, tl1 = m1 / P, p1 = m1 % P;
      float* w0 = ws + (size_t)(t0 + tl0) * out_f + (p0 * Q + q) * Rr;
      float* w1 = ws + (size_t)(t0 + tl1) * out_f + (p1 * Q + q) * Rr;
#pragma unroll
      for (int rt = 0; rt < RT; ++rt) {
        const int r = rt * 8 + 2 * t4;
        if (r < Rr) {
          if constexpr (CL > 1) {  // into this block's sY; the cluster sums it below
            float* sy = reinterpret_cast<float*>(smem + C::y_off) + ql * C::Mr * C::Rrp;
            *reinterpret_cast<float2*>(sy + m0 * C::Rrp + r) =
                make_float2(yv[mg][rt][0], yv[mg][rt][1]);
            *reinterpret_cast<float2*>(sy + m1 * C::Rrp + r) =
                make_float2(yv[mg][rt][2], yv[mg][rt][3]);
          } else {
            if (ablate) continue;
            if (tl0 < tt_valid) red_add_v2(w0 + r, yv[mg][rt][0], yv[mg][rt][1]);
            if (tl1 < tt_valid) red_add_v2(w1 + r, yv[mg][rt][2], yv[mg][rt][3]);
          }
        }
      }
    }
  }

  if constexpr (CL > 1) {  // ---- sum the CL links through distributed shared memory
#if __CUDA_ARCH__ >= 900
    namespace cg = cooperative_groups;
    cg::cluster_group cluster = cg::this_cluster();
    cluster.sync();  // every block's sY is written and visible to the whole cluster
    const int cr = (int)cluster.block_rank();
    constexpr int Rh = Rr / 2;
    const int rows = tt_valid * P, n = qc_valid * rows * Rh;
    float* peer[CL];
#pragma unroll
    for (int s = 0; s < CL; ++s)
      peer[s] = cluster.map_shared_rank(reinterpret_cast<float*>(smem + C::y_off), s);
    for (int e = cr * NT + tid; e < n; e += CL * NT) {  // the cluster splits the outputs
      const int ql = e / (rows * Rh), rem = e % (rows * Rh), m = rem / Rh, r = 2 * (rem % Rh);
      const int off = (ql * C::Mr + m) * C::Rrp + r;
      float2 v = *reinterpret_cast<const float2*>(peer[0] + off);
#pragma unroll
      for (int s = 1; s < CL; ++s) {
        const float2 w = *reinterpret_cast<const float2*>(peer[s] + off);
        v.x += w.x;
        v.y += w.y;
      }
      const int tl = m / P, p = m % P;
      if (!ablate)
        red_add_v2(ws + (size_t)(t0 + tl) * out_f + (p * Q + q0 + ql) * Rr + r, v.x, v.y);
    }
    cluster.sync();  // no block leaves while a peer may still read its sY
#endif
  }

  // ---- design B: one counter per (token tile, q chunk); the last of its R * nkc blocks
  // converts those rows and clears them, 8 float4 loads in flight before any store
  if (ablate == 2) return;
  __shared__ bool is_last;
  unsigned int* ctr = tile_done + tti * C::nqc + qci;
  __threadfence();
  __syncthreads();
  if (tid == 0) is_last = atomicAdd(ctr, 1u) == unsigned(R * C::nkc) - 1;
  __syncthreads();
  if (is_last) {
    __threadfence();
    constexpr int R4 = Rr / 4, kIn = 8;
    const int per_tp = qc_valid * R4, n4 = tt_valid * P * per_tp;
    float4* ws4 = reinterpret_cast<float4*>(ws);
    for (int base = 0; base < n4; base += kIn * NT) {
      float4 v[kIn];
      int idx[kIn];
#pragma unroll
      for (int s = 0; s < kIn; ++s) {
        const int e = base + tid + s * NT;
        if (e < n4) {
          const int tp = e / per_tp, tl = tp / P, p = tp % P;
          idx[s] = (t0 + tl) * (out_f / 4) + (p * Q + q0) * R4 + e % per_tp;
          v[s] = __ldcg(ws4 + idx[s]);
        } else {
          idx[s] = -1;
        }
      }
#pragma unroll
      for (int s = 0; s < kIn; ++s) {
        if (idx[s] >= 0) {
          uint2 h;
          h.x = O::pack_f2(v[s].x, v[s].y);
          h.y = O::pack_f2(v[s].z, v[s].w);
          reinterpret_cast<uint2*>(y)[idx[s]] = h;
          ws4[idx[s]] = make_float4(0.f, 0.f, 0.f, 0.f);
        }
      }
    }
    if (tid == 0) *ctr = 0;
  }
}

// ---- host ---------------------------------------------------------------------------------
struct Call {  // one forward call, type-erased
  // modes and tiling; names differ from the macro parameters below (a macro would rewrite them)
  int64_t i1, i2, i3, o1, o2, o3, rank, kc, qc, tt, mg, nt, ks, cl;
  bool bf16;
  int T;
  const void *x, *a1, *b2, *c3;
  float* ws;
  void* y;
  unsigned int* td;
  int ablate;
  cudaStream_t stream;
};

template <class M, class E, int R, int KC, int QC, int TT, int MG, int NT, int KS, int CL>
void launch(const Call& c) {
  using C = Cfg<M, R, KC, QC, TT, MG, CL>;
  auto kernel = v3g_kernel<M, E, R, KC, QC, TT, MG, NT, KS, CL>;
  static bool attr = false;
  if (!attr) {
    C10_CUDA_CHECK(cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize,
                                        (int)C::smem));
    attr = true;
  }
  const int ntt = (c.T + TT - 1) / TT;
  const unsigned grid = R * C::nkc * C::nqc * ntt;
  const E* x = static_cast<const E*>(c.x);
  const E* a1 = static_cast<const E*>(c.a1);
  const E* b2 = static_cast<const E*>(c.b2);
  const E* c3 = static_cast<const E*>(c.c3);
  E* y = static_cast<E*>(c.y);
  if constexpr (CL > 1) {  // cluster launch: CL consecutive blocks share distributed smem
    cudaLaunchConfig_t cfg = {};
    cfg.gridDim = dim3(grid);
    cfg.blockDim = dim3(NT);
    cfg.dynamicSmemBytes = C::smem;
    cfg.stream = c.stream;
    cudaLaunchAttribute attr_cl[1];
    attr_cl[0].id = cudaLaunchAttributeClusterDimension;
    attr_cl[0].val.clusterDim.x = CL;
    attr_cl[0].val.clusterDim.y = 1;
    attr_cl[0].val.clusterDim.z = 1;
    cfg.attrs = attr_cl;
    cfg.numAttrs = 1;
    C10_CUDA_CHECK(cudaLaunchKernelEx(&cfg, kernel, x, a1, b2, c3, c.ws, y, c.td, c.T, c.ablate));
  } else {
    kernel<<<grid, NT, C::smem, c.stream>>>(x, a1, b2, c3, c.ws, y, c.td, c.T, c.ablate);
  }
  C10_CUDA_KERNEL_LAUNCH_CHECK();
}

// X(dtype_is_bf16, E, ni, nj, nk, P, Q, Rr, R, KC, QC, TT, MG, NTH, KSP, CLS)
#define V3G_MATCH(c, BF, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS)                        \
  ((c).bf16 == BF && (c).i1 == NI && (c).i2 == NJ && (c).i3 == NK && (c).o1 == P &&       \
   (c).o2 == Q && (c).o3 == RR && (c).rank == R && (c).kc == KC && (c).qc == QC &&       \
   (c).tt == TT && (c).mg == MG && (c).nt == NTH && (c).ks == KSP && (c).cl == CLS)

#define V3G_LAUNCH_CASE(BF, E, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS)                    \
  if (V3G_MATCH(c, BF, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS)) {                         \
    launch<Modes<NI, NJ, NK, P, Q, RR>, E, R, KC, QC, TT, MG, NTH, KSP, CLS>(c);                          \
    return true;                                                                           \
  }
#define V3G_SMEM_CASE(BF, E, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS)                      \
  if (V3G_MATCH(c, BF, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS))                           \
    return (int64_t)Cfg<Modes<NI, NJ, NK, P, Q, RR>, R, KC, QC, TT, MG, CLS>::smem;
#define V3G_LIST_CASE(BF, E, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS)                      \
  out.push_back({BF, NI, NJ, NK, P, Q, RR, R, KC, QC, TT, MG, NTH, KSP, CLS});

// one translation unit per shape defines these three with its own list
#define V3G_DEFINE_UNIT(NAME, LIST)                                                        \
  bool launch_##NAME(const v3g::Call& c) {                                                 \
    using namespace v3g;                                                                   \
    LIST(V3G_LAUNCH_CASE) return false;                                                    \
  }                                                                                        \
  int64_t smem_##NAME(const v3g::Call& c) {                                                \
    using namespace v3g;                                                                   \
    LIST(V3G_SMEM_CASE) return 0;                                                          \
  }                                                                                        \
  void list_##NAME(std::vector<std::vector<int64_t>>& out) { LIST(V3G_LIST_CASE) }

}  // namespace v3g
