#!/usr/bin/env python3
"""Turn a tools/v3g_sweep.py JSON into src/factorized_inference/v3g_tuned.py: the fastest correct
V3G tiling per (modes, R, T) on that GPU. PreparedTRKernel uses it for T in the table and the
nearest smaller measured T otherwise.

    python tools/gen_v3g_tuned.py results/h100/qwen/v3g_sweep.json
"""
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from qwen_shapes import SHAPES  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "factorized_inference" / "v3g_tuned.py"
ASSIGN = ((8, 12, 20), (12, 10, 24))


def main():
    src = pathlib.Path(sys.argv[1])
    data = json.loads(src.read_text())
    best = {}
    for r in data["rows"]:
        if not r["correct"] or r["shape"] == "assign":  # the assignment keeps V3 / V3T
            continue
        ins, outs, _ = SHAPES[r["shape"]]
        key = (ins + outs, r["rank"], r["tokens"])
        if key not in best or r["v3g_us"] < best[key][1]:
            best[key] = (tuple(r["tiling"]), r["v3g_us"])
    table = {}
    for (modes, R, T), (t, _) in sorted(best.items()):
        table.setdefault((modes, R), {})[T] = t
    lines = [f'"""Generated by tools/gen_v3g_tuned.py from {src} ({data["device"]}).',
             "(ni, nj, nk, P, Q, Rr), R -> {T: (kc, qc, tt, mg, nt, ks, cl)}: the fastest correct V3G tiling.",
             '"""', "V3G_TUNED = {"]
    for (modes, R), per_t in table.items():
        lines.append(f"    ({modes}, {R}): {per_t},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(table)} (modes, R) entries)")


if __name__ == "__main__":
    main()
