#!/usr/bin/env python3
"""Generate the compiled V3G tilings (src/factorized_inference/csrc/v3g/).

For every Qwen3.8-27B shape (tools/qwen_shapes.py) and R = 8, 16, BF16:
  T = 1 group: TT = 16 / P token rows (one m16 tile), KC in {2, 4}, QC in {ceil(Q/2), ceil(Q/4)}
  T > 1 group: TT = 4,                                KC in {1, 2, 4}, same QC
  each also with NT = 256 / 512 threads, KS = 1 (the k-split KS = 2 / 4 of 28 Sep never won) and
  CL = 1 / 2 / 4 / 8: cluster of CL ring links summed in distributed shared memory, kept if the
  extra sY buffer still fits
kept if the block fits the H100's 227 KB of shared memory (the same map as Cfg in v3g.cuh).
Plus the assignment's modes in FP16 with the V3T defaults, to compare V3G with V3T.

Writes tilings.h and one unit_<shape>.cu per shape (compiled in parallel by ninja).

    python tools/gen_v3g_tilings.py
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from qwen_shapes import SHAPES  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parents[1] / "src" / "factorized_inference" / "csrc" / "v3g"
SMEM_LIMIT = 232448 - 1024  # H100 opt-in per block, minus static shared memory


def r16(v):
    return -(-v // 16) * 16


def a128(v):
    return (v + 127) // 128 * 128


def smem(ins, outs, R, KC, QC, TT, CL=1):
    (ni, nj, _), (P, _, Rr) = ins, outs
    Rc, Rrs, K2p = r16(R), r16(Rr) + 8, r16(nj * R)
    o = a128(2 * K2p * (QC * Rc + 8))
    o = a128(o + 2 * ni * P * R)
    o = a128(o + 2 * KC * Rc * Rrs)
    o = a128(o + 4 * KC * TT * ni * nj)
    o = a128(o + 2 * KC * r16(TT * P) * (K2p + 8))
    return a128(o + 4 * QC * r16(TT * P) * r16(Rr)) if CL > 1 else o


def tilings(ins, outs, R):
    P, Q = outs[0], outs[1]
    qcs = sorted({-(-Q // 2), -(-Q // 4)}, reverse=True)
    rows = []
    for TT, kcs in ((max(1, 16 // P), (2, 4)), (4, (1, 2, 4))):
        for KC in kcs:
            for QC in qcs:
                if (TT * P) % 16 == 0 and smem(ins, outs, R, KC, QC, TT) <= SMEM_LIMIT:
                    rows.append((KC, QC, TT, 1))
    return sorted(set(rows))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    units = {}
    for name, (ins, outs, _) in SHAPES.items():
        units[name] = [(1, "__nv_bfloat16", *ins, *outs, R, *t, nt, 1, cl)
                       for R in (8, 16) for t in tilings(ins, outs, R)
                       for nt in (256, 512) for cl in (1, 2, 4, 8)
                       if cl == 1 or smem(ins, outs, R, t[0], t[1], t[2], cl) <= SMEM_LIMIT]
    units["assign"] = [(0, "__half", 8, 12, 20, 12, 10, 24, 8, 5, 5, 4, 1, 256, 1, 1),
                       (0, "__half", 8, 12, 20, 12, 10, 24, 16, 5, 10, 4, 1, 256, 1, 1)]
    lines = ["// generated by tools/gen_v3g_tilings.py: X(bf16?, E, ni, nj, nk, P, Q, Rr, R, KC, QC, TT, MG, NT, KS, CL)",
             "#pragma once"]
    for name, rows in units.items():
        body = " \\\n".join(f"  X({', '.join(map(str, r))})" for r in rows)
        lines.append(f"#define V3G_LIST_{name}(X) \\\n{body}\n")
    (OUT / "tilings.h").write_text("\n".join(lines) + "\n")
    for name in units:
        (OUT / f"unit_{name}.cu").write_text(
            f'// generated by tools/gen_v3g_tilings.py\n#include "v3g.cuh"\n#include "tilings.h"\n'
            f"V3G_DEFINE_UNIT({name}, V3G_LIST_{name})\n")
    (OUT / "units.h").write_text(
        "// generated by tools/gen_v3g_tilings.py\n#define V3G_UNITS(X) "
        + " ".join(f"X({n})" for n in units) + "\n")
    total = sum(len(r) for r in units.values())
    print(f"{total} variants in {len(units)} units -> {OUT}")
    for n, r in units.items():
        print(f"  {n:12s} {len(r)}")


if __name__ == "__main__":
    main()
